// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpnvjpywkxuhmzvntzyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wbnZqcHl3a3h1aG16dm50enlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzUzOTMsImV4cCI6MjA2NTE1MTM5M30.CIf6tfYhygO4SsmIS4UvI4CPSs6_06LaDDJXYrySbUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);